language: emacs-lisp

env:
  matrix:
    - EMACS=emacs24

before_install:
  - mkdir -p ~/.local/bin
  - export PATH="~/.local/bin:$PATH"
  - export PATH=/opt/ghc/7.8.4/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.8.4

install:
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - stack --no-terminal --skip-ghc-check setup

script:
  - lsb_release -a
  - stack --no-terminal --skip-ghc-check install --ghc-options=-O0
  - cd elisp && make && make test

notifications:
  email: false

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
